server:
  port: 8999
spring:
  main:
    web-application-type: none
  application:
    name: sh-service-provider
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    suffix: .ftl
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lifeng
    username: root
    password: root
    druid:
      db-type: mysql
      initial-size: 5
      max-active: 10
      min-idle: 1
      max-wait: 60000
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
    servlet:
      multipart:
        max-file-size: 1023MB
        max-request-size: 1024MB

dubbo:
  application:
    name: dubbo-sh-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
    #    address: 106.55.16.89:2181
    timeout: 20000
    file: ./dubbo-cache-provide-sh
  version: 1.0.0
  scan:
    base-packages: com.rushuni.sh.provider
# MyBatis-Plus
mybatis-plus:
  # xml文件路径
  mapper-locations: classpath:mapper/*.xml
  # 实体类路径
  type-aliases-package: com.rushuni.sh.common.domain
  configuration:
    # 驼峰转换
    map-underscore-to-camel-case: true
    # 是否开启缓存
    cache-enabled: false
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

out-put-path: E:\Javastage4\lifeng-smart-health\sh-service-wx\src\main\resources\templates